---
- name: Slugify local directory name
  set_fact:
    hugo_repo_slug: "{{ hugo_dir | regex_replace('/', '-') }}"

- name: Install hugo and dependencies
  become: True
  apt:
    package:
      - acl   # needed for become_user
      - git
      - hugo

- name: Ensure hugo user exists
  become: True
  user:
    name: "{{ hugo_user }}"
    createhome: yes
    home: "{{ hugo_home }}"

- name: Ensure .ssh directory exists
  become: True
  become_user: "{{ hugo_user }}"
  file:
    path: "{{ hugo_home }}/.ssh"
    state: directory
    mode: 0700
  when: hugo_repo_ssh_key != 'changeme'

- name: Configure ssh key
  become: True
  become_user: "{{ hugo_user }}"
  template:
    src: id_rsa.j2
    dest: "{{ hugo_home }}/.ssh/id_rsa"
    mode: 0600
  when: hugo_repo_ssh_key != 'changeme'

- name: Ensure checkout location exists
  become: True
  file:
    dest: "{{ hugo_dir }}"
    state: directory
    owner: "{{ hugo_user }}"
    group: "{{ hugo_user }}"
    mode: 0755

- name: Check out the repository
  become: True
  become_user: "{{ hugo_user }}"
  git:
    repo: "{{ hugo_repo }}"
    dest: "{{ hugo_dir }}"
    version: "{{ hugo_repo_version }}"
    accept_hostkey: yes
    force: yes
  notify: restart hugo

- name: Configure systemd pull service for hugo
  become: True
  template:
    src: "hugo-pull.{{ item }}.j2"
    dest: "/etc/systemd/system/hugo-{{ hugo_repo_slug }}-pull.{{ item }}"
  with_items:
    - service
    - timer
  register: hugo_timer

- name: Start hugo timer
  become: True
  systemd:
    daemon_reload: yes
    name: "hugo-{{ hugo_repo_slug }}-pull.timer"
    state: started
    enabled: yes
  when: hugo_timer.changed

- name: Configure hugo
  become: True
  template:
    src: "hugo.service.j2"
    dest: "/etc/systemd/system/hugo-{{ hugo_repo_slug }}.service"
  register: hugo_service

- name: Start hugo
  become: True
  systemd:
    daemon_reload: yes
    name: "hugo-{{ hugo_repo_slug }}.service"
    state: restarted
    enabled: yes
  when: hugo_service.changed
